/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function BizWomanBlack(props) {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/3d/wellcoPeople/biz-woman-black.gltf', draco('/draco-gltf/'))
  return (
    <group ref={group} {...props} dispose={null}scale={[.01,.01,.01]} position={[-3, 0.1, 3]}>
      <mesh material={materials.PackedMaterial0} geometry={nodes.Eyelashes.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes['default'].geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_0.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_1.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_2.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_3.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_4.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.mesh_2_5.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.Shoes.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.Hair.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.Tops.geometry} />
      <mesh material={materials.PackedMaterial0} geometry={nodes.Bottoms.geometry} />
    </group>
  )
}
