/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useLoader, useFrame } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { draco } from 'drei'

export default function Booth(props) {
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/3d/wellco/wellco-no-people.gltf', draco('/draco-gltf/'))
  
  const group = useRef()
  // const actions = useRef()
  // const [mixer] = useState(() => new THREE.AnimationMixer())
  // useFrame((state, delta) => mixer.update(delta))
  // useEffect(() => {
  //   actions.current = {
  //     'Take 01': mixer.clipAction(animations[0], group.current),
  //   }
  //   return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  // }, [])
  
  // useFrame(state => {
  //   console.log(group.current)
  // })


  return (
    <group ref={group} {...props} dispose={null}>
      <scene>
        <group name="Line037_Mesh020">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Line037_Mesh020_White_Lam_Matte_.geometry}
            name="Line037_Mesh020_White_Lam_Matte_"
          />
          <mesh
            material={materials.universe_of_expression}
            geometry={nodes.Line037_Mesh020_universe_of_expression.geometry}
            name="Line037_Mesh020_universe_of_expression"
          />
        </group>
        <group name="30WHHB_Mesh150">
          <mesh
            material={materials['Chrome.001']}
            geometry={nodes['30WHHB_Mesh150_Chrome001'].geometry}
            name="30WHHB_Mesh150_Chrome001"
          />
          <mesh
            material={materials.black}
            geometry={nodes['30WHHB_Mesh150_black'].geometry}
            name="30WHHB_Mesh150_black"
          />
          <mesh
            material={materials['White_Lam_Matte_.001']}
            geometry={nodes['30WHHB_Mesh150_White_Lam_Matte_001'].geometry}
            name="30WHHB_Mesh150_White_Lam_Matte_001"
          />
        </group>
        <group name="ZOEY_BARSTOOL_BLACK002_Mesh152">
          <mesh
            material={materials['Chrome.001']}
            geometry={nodes.ZOEY_BARSTOOL_BLACK002_Mesh152_Chrome001.geometry}
            name="ZOEY_BARSTOOL_BLACK002_Mesh152_Chrome001"
          />
          <mesh
            material={materials.black}
            geometry={nodes.ZOEY_BARSTOOL_BLACK002_Mesh152_black.geometry}
            name="ZOEY_BARSTOOL_BLACK002_Mesh152_black"
          />
          <mesh
            material={materials['White_Lam_Matte_.001']}
            geometry={nodes.ZOEY_BARSTOOL_BLACK002_Mesh152_White_Lam_Matte_001.geometry}
            name="ZOEY_BARSTOOL_BLACK002_Mesh152_White_Lam_Matte_001"
          />
        </group>
        <group name="ZOEY_BARSTOOL_BLACK003_Mesh153">
          <mesh
            material={materials['Chrome.001']}
            geometry={nodes.ZOEY_BARSTOOL_BLACK003_Mesh153_Chrome001.geometry}
            name="ZOEY_BARSTOOL_BLACK003_Mesh153_Chrome001"
          />
          <mesh
            material={materials.black}
            geometry={nodes.ZOEY_BARSTOOL_BLACK003_Mesh153_black.geometry}
            name="ZOEY_BARSTOOL_BLACK003_Mesh153_black"
          />
          <mesh
            material={materials['White_Lam_Matte_.001']}
            geometry={nodes.ZOEY_BARSTOOL_BLACK003_Mesh153_White_Lam_Matte_001.geometry}
            name="ZOEY_BARSTOOL_BLACK003_Mesh153_White_Lam_Matte_001"
          />
        </group>
        <group name="Tube008_Mesh384">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Tube008_Mesh384_White_Lam_Matte_.geometry}
            name="Tube008_Mesh384_White_Lam_Matte_"
          />
          <mesh
            material={materials['Stemline_blue.001']}
            geometry={nodes.Tube008_Mesh384_Stemline_blue001.geometry}
            name="Tube008_Mesh384_Stemline_blue001"
          />
        </group>
        <group name="Tube009_Mesh385">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Tube009_Mesh385_White_Lam_Matte_.geometry}
            name="Tube009_Mesh385_White_Lam_Matte_"
          />
          <mesh
            material={materials['Stemline_blue.001']}
            geometry={nodes.Tube009_Mesh385_Stemline_blue001.geometry}
            name="Tube009_Mesh385_Stemline_blue001"
          />
        </group>
        <group name="Box104_Mesh386">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Box104_Mesh386_White_Lam_Matte_.geometry}
            name="Box104_Mesh386_White_Lam_Matte_"
          />
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.Box104_Mesh386_Stemline_blue.geometry}
            name="Box104_Mesh386_Stemline_blue"
          />
        </group>
        <group name="Box105_Mesh387">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Box105_Mesh387_White_Lam_Matte_.geometry}
            name="Box105_Mesh387_White_Lam_Matte_"
          />
          <mesh
            material={materials['Stemline_blue.001']}
            geometry={nodes.Box105_Mesh387_Stemline_blue001.geometry}
            name="Box105_Mesh387_Stemline_blue001"
          />
        </group>
        <group name="Box106_Mesh388">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Box106_Mesh388_White_Lam_Matte_.geometry}
            name="Box106_Mesh388_White_Lam_Matte_"
          />
          <mesh
            material={materials['Stemline_blue.001']}
            geometry={nodes.Box106_Mesh388_Stemline_blue001.geometry}
            name="Box106_Mesh388_Stemline_blue001"
          />
        </group>
        <group name="Box107_Mesh389">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Box107_Mesh389_White_Lam_Matte_.geometry}
            name="Box107_Mesh389_White_Lam_Matte_"
          />
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.Box107_Mesh389_Stemline_blue.geometry}
            name="Box107_Mesh389_Stemline_blue"
          />
        </group>
        <group name="Tube010_Mesh390">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Tube010_Mesh390_White_Lam_Matte_.geometry}
            name="Tube010_Mesh390_White_Lam_Matte_"
          />
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.Tube010_Mesh390_Stemline_blue.geometry}
            name="Tube010_Mesh390_Stemline_blue"
          />
        </group>
        <group name="Tube007_Mesh391">
          <mesh
            material={materials.White_Lam_Matte_}
            geometry={nodes.Tube007_Mesh391_White_Lam_Matte_.geometry}
            name="Tube007_Mesh391_White_Lam_Matte_"
          />
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.Tube007_Mesh391_Stemline_blue.geometry}
            name="Tube007_Mesh391_Stemline_blue"
          />
        </group>
        <group name="logo_Curve001">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo_Curve001_Stemline_blue.geometry}
            name="logo_Curve001_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo_Curve001_stemlin.geometry}
            name="logo_Curve001_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo_Curve001_WellCo-1'].geometry}
            name="logo_Curve001_WellCo-1"
          />
        </group>
        <group name="logo001_Curve009">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo001_Curve009_Stemline_blue.geometry}
            name="logo001_Curve009_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo001_Curve009_stemlin.geometry}
            name="logo001_Curve009_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo001_Curve009_WellCo-1'].geometry}
            name="logo001_Curve009_WellCo-1"
          />
        </group>
        <group name="logo002_Curve010">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo002_Curve010_Stemline_blue.geometry}
            name="logo002_Curve010_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo002_Curve010_stemlin.geometry}
            name="logo002_Curve010_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo002_Curve010_WellCo-1'].geometry}
            name="logo002_Curve010_WellCo-1"
          />
        </group>
        <group name="logo003_Curve011">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo003_Curve011_Stemline_blue.geometry}
            name="logo003_Curve011_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo003_Curve011_stemlin.geometry}
            name="logo003_Curve011_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo003_Curve011_WellCo-1'].geometry}
            name="logo003_Curve011_WellCo-1"
          />
        </group>
        <group name="logo004_Curve012">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo004_Curve012_Stemline_blue.geometry}
            name="logo004_Curve012_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo004_Curve012_stemlin.geometry}
            name="logo004_Curve012_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo004_Curve012_WellCo-1'].geometry}
            name="logo004_Curve012_WellCo-1"
          />
        </group>
        <group name="logo005_Curve013">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo005_Curve013_Stemline_blue.geometry}
            name="logo005_Curve013_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo005_Curve013_stemlin.geometry}
            name="logo005_Curve013_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo005_Curve013_WellCo-1'].geometry}
            name="logo005_Curve013_WellCo-1"
          />
        </group>
        <group name="logo006_Curve014">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo006_Curve014_Stemline_blue.geometry}
            name="logo006_Curve014_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo006_Curve014_stemlin.geometry}
            name="logo006_Curve014_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo006_Curve014_WellCo-1'].geometry}
            name="logo006_Curve014_WellCo-1"
          />
        </group>
        <group name="logo007_Curve015">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo007_Curve015_Stemline_blue.geometry}
            name="logo007_Curve015_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo007_Curve015_stemlin.geometry}
            name="logo007_Curve015_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo007_Curve015_WellCo-1'].geometry}
            name="logo007_Curve015_WellCo-1"
          />
        </group>
        <group name="logo008_Curve016">
          <mesh
            material={materials.Stemline_blue}
            geometry={nodes.logo008_Curve016_Stemline_blue.geometry}
            name="logo008_Curve016_Stemline_blue"
          />
          <mesh
            material={materials.stemlin}
            geometry={nodes.logo008_Curve016_stemlin.geometry}
            name="logo008_Curve016_stemlin"
          />
          <mesh
            material={materials['WellCo-1']}
            geometry={nodes['logo008_Curve016_WellCo-1'].geometry}
            name="logo008_Curve016_WellCo-1"
          />
        </group>
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder008_Cylinder010.geometry}
          name="Cylinder008_Cylinder010"
        />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder000_Cylinder014.geometry}
          name="Cylinder000_Cylinder014"
        />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder002_Cylinder016.geometry}
          name="Cylinder002_Cylinder016"
        />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder004_Cylinder018.geometry}
          name="Cylinder004_Cylinder018"
        />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder006_Cylinder020.geometry}
          name="Cylinder006_Cylinder020"
        />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder010_Cylinder022.geometry}
          name="Cylinder010_Cylinder022"
        />
        <mesh material={materials.None} geometry={nodes.Cube.geometry} name="Cube" />
        <mesh
          material={materials.None}
          geometry={nodes.Cylinder012_Cylinder024.geometry}
          name="Cylinder012_Cylinder024"
        />
        <mesh material={materials.None} geometry={nodes.Text011_Mesh498.geometry} name="Text011_Mesh498" />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder009_Cylinder011.geometry}
          name="Cylinder009_Cylinder011"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder001_Cylinder015.geometry}
          name="Cylinder001_Cylinder015"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder003_Cylinder017.geometry}
          name="Cylinder003_Cylinder017"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder005_Cylinder019.geometry}
          name="Cylinder005_Cylinder019"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder007_Cylinder021.geometry}
          name="Cylinder007_Cylinder021"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder011_Cylinder023.geometry}
          name="Cylinder011_Cylinder023"
        />
        <mesh
          material={materials.Corporate_Navy}
          geometry={nodes.Cylinder013_Cylinder025.geometry}
          name="Cylinder013_Cylinder025"
        />
        <mesh material={materials.Corporate_Navy} geometry={nodes.Box008_Mesh033.geometry} name="Box008_Mesh033" />
        <mesh material={materials.Corporate_Navy} geometry={nodes.Box007_Mesh034.geometry} name="Box007_Mesh034" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Cube001.geometry} name="Cube001" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Line036_Mesh021.geometry} name="Line036_Mesh021" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box005_Mesh022.geometry} name="Box005_Mesh022" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box006_Mesh023.geometry} name="Box006_Mesh023" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box004_Mesh024.geometry} name="Box004_Mesh024" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Line032_Mesh025.geometry} name="Line032_Mesh025" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Line031_Mesh026.geometry} name="Line031_Mesh026" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box003_Mesh027.geometry} name="Box003_Mesh027" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Line033_Mesh028.geometry} name="Line033_Mesh028" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Line043_Mesh038.geometry} name="Line043_Mesh038" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box023_Mesh134.geometry} name="Box023_Mesh134" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.SWAN014_Mesh372.geometry} name="SWAN014_Mesh372" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.SWAN017_Mesh375.geometry} name="SWAN017_Mesh375" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Text001_Mesh499.geometry} name="Text001_Mesh499" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box055_Mesh504.geometry} name="Box055_Mesh504" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box056_Mesh505.geometry} name="Box056_Mesh505" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Tube001_Mesh506.geometry} name="Tube001_Mesh506" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box057_Mesh507.geometry} name="Box057_Mesh507" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Tube002_Mesh508.geometry} name="Tube002_Mesh508" />
        <mesh material={materials.White_Lam_Matte_} geometry={nodes.Box058_Mesh509.geometry} name="Box058_Mesh509" />
        <mesh
          material={materials.White_Lam_Matte_}
          geometry={nodes.SWAN014001_Mesh002.geometry}
          name="SWAN014001_Mesh002"
        />
        <mesh
          material={materials.White_Lam_Matte_}
          geometry={nodes.SWAN017001_Mesh005.geometry}
          name="SWAN017001_Mesh005"
        />
        <mesh material={materials['Chrome.001']} geometry={nodes.Cube002.geometry} name="Cube002" />
        <mesh material={materials.screen} geometry={nodes.screen.geometry} name="screen" />
        <mesh material={materials.Material} geometry={nodes.Ceiling_Mesh001.geometry} name="Ceiling_Mesh001" />
        <mesh material={materials.wood_floor} geometry={nodes.Line041_Mesh029.geometry} name="Line041_Mesh029" />
        <mesh material={materials.wood_floor} geometry={nodes.Line038_Mesh030.geometry} name="Line038_Mesh030" />
        <mesh material={materials.wood_floor} geometry={nodes.Line042_Mesh031.geometry} name="Line042_Mesh031" />
        <mesh material={materials.wood_floor} geometry={nodes.Line039_Mesh032.geometry} name="Line039_Mesh032" />
        <mesh material={materials.wood_floor} geometry={nodes.Line046_Mesh135.geometry} name="Line046_Mesh135" />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Rectangle003_Mesh035.geometry}
          name="Rectangle003_Mesh035"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Rectangle002_Mesh036.geometry}
          name="Rectangle002_Mesh036"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Samsung_55_LED002_Mesh127.geometry}
          name="Samsung_55_LED002_Mesh127"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Samsung_55_LED003_Mesh129.geometry}
          name="Samsung_55_LED003_Mesh129"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Leg_pegs004_Mesh377.geometry}
          name="Leg_pegs004_Mesh377"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Samsung_55_LED_Mesh502.geometry}
          name="Samsung_55_LED_Mesh502"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Samsung_55_LED001_Mesh503.geometry}
          name="Samsung_55_LED001_Mesh503"
        />
        <mesh
          material={materials.Black_Lam_Matte_}
          geometry={nodes.Leg_pegs000_Mesh007.geometry}
          name="Leg_pegs000_Mesh007"
        />
        <mesh material={materials.glowing} geometry={nodes.Line044_Mesh037.geometry} name="Line044_Mesh037" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder194_Mesh077.geometry} name="Cylinder194_Mesh077" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder182_Mesh083.geometry} name="Cylinder182_Mesh083" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder188_Mesh089.geometry} name="Cylinder188_Mesh089" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder176_Mesh095.geometry} name="Cylinder176_Mesh095" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder170_Mesh101.geometry} name="Cylinder170_Mesh101" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder103_Mesh106.geometry} name="Cylinder103_Mesh106" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder110_Mesh113.geometry} name="Cylinder110_Mesh113" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder097_Mesh118.geometry} name="Cylinder097_Mesh118" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder091_Mesh124.geometry} name="Cylinder091_Mesh124" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder152_Mesh412.geometry} name="Cylinder152_Mesh412" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder164_Mesh418.geometry} name="Cylinder164_Mesh418" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder158_Mesh424.geometry} name="Cylinder158_Mesh424" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder122_Mesh430.geometry} name="Cylinder122_Mesh430" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder116_Mesh436.geometry} name="Cylinder116_Mesh436" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder134_Mesh442.geometry} name="Cylinder134_Mesh442" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder128_Mesh448.geometry} name="Cylinder128_Mesh448" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder140_Mesh454.geometry} name="Cylinder140_Mesh454" />
        <mesh material={materials.glowing} geometry={nodes.Cylinder146_Mesh460.geometry} name="Cylinder146_Mesh460" />
        <mesh material={materials.Elzonris_lightbox} geometry={nodes.Arc005_Mesh039.geometry} name="Arc005_Mesh039" />
        <mesh material={materials.Elzonris_lightbox} geometry={nodes.Box011_Mesh041.geometry} name="Box011_Mesh041" />
        <mesh material={materials.Elzonris_lightbox} geometry={nodes.Box012_Mesh043.geometry} name="Box012_Mesh043" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Arc004_Mesh040.geometry} name="Arc004_Mesh040" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Box010_Mesh042.geometry} name="Box010_Mesh042" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Box009_Mesh044.geometry} name="Box009_Mesh044" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Arc006_Mesh045.geometry} name="Arc006_Mesh045" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Box013_Mesh046.geometry} name="Box013_Mesh046" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Box014_Mesh047.geometry} name="Box014_Mesh047" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Box024_Mesh133.geometry} name="Box024_Mesh133" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line059_Mesh398.geometry} name="Line059_Mesh398" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line060_Mesh399.geometry} name="Line060_Mesh399" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line061_Mesh400.geometry} name="Line061_Mesh400" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line055_Mesh401.geometry} name="Line055_Mesh401" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line053_Mesh402.geometry} name="Line053_Mesh402" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line054_Mesh403.geometry} name="Line054_Mesh403" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line056_Mesh404.geometry} name="Line056_Mesh404" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line057_Mesh405.geometry} name="Line057_Mesh405" />
        <mesh material={materials.Brushed_Metal} geometry={nodes.Line058_Mesh406.geometry} name="Line058_Mesh406" />
        <mesh material={materials.glowing_blue} geometry={nodes.Box017_Mesh048.geometry} name="Box017_Mesh048" />
        <mesh material={materials.glowing_blue} geometry={nodes.Box059_Mesh510.geometry} name="Box059_Mesh510" />
        <mesh material={materials.PI} geometry={nodes.Box048_Mesh060.geometry} name="Box048_Mesh060" />
        <mesh material={materials.PI} geometry={nodes.Box042_Mesh066.geometry} name="Box042_Mesh066" />
        <mesh material={materials.PI} geometry={nodes.Box034_Mesh139.geometry} name="Box034_Mesh139" />
        <mesh material={materials.PI} geometry={nodes.Box035_Mesh140.geometry} name="Box035_Mesh140" />
        <mesh material={materials.PI} geometry={nodes.Box036_Mesh141.geometry} name="Box036_Mesh141" />
        <mesh material={materials.PI} geometry={nodes.Box028_Mesh145.geometry} name="Box028_Mesh145" />
        <mesh material={materials.PI} geometry={nodes.Box029_Mesh146.geometry} name="Box029_Mesh146" />
        <mesh material={materials.PI} geometry={nodes.Box030_Mesh147.geometry} name="Box030_Mesh147" />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder189_Mesh072.geometry}
          name="Cylinder189_Mesh072"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder190_Mesh073.geometry}
          name="Cylinder190_Mesh073"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder191_Mesh074.geometry}
          name="Cylinder191_Mesh074"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder192_Mesh075.geometry}
          name="Cylinder192_Mesh075"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder193_Mesh076.geometry}
          name="Cylinder193_Mesh076"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder177_Mesh078.geometry}
          name="Cylinder177_Mesh078"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder178_Mesh079.geometry}
          name="Cylinder178_Mesh079"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder179_Mesh080.geometry}
          name="Cylinder179_Mesh080"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder180_Mesh081.geometry}
          name="Cylinder180_Mesh081"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder181_Mesh082.geometry}
          name="Cylinder181_Mesh082"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder183_Mesh084.geometry}
          name="Cylinder183_Mesh084"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder184_Mesh085.geometry}
          name="Cylinder184_Mesh085"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder185_Mesh086.geometry}
          name="Cylinder185_Mesh086"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder186_Mesh087.geometry}
          name="Cylinder186_Mesh087"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder187_Mesh088.geometry}
          name="Cylinder187_Mesh088"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder171_Mesh090.geometry}
          name="Cylinder171_Mesh090"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder172_Mesh091.geometry}
          name="Cylinder172_Mesh091"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder173_Mesh092.geometry}
          name="Cylinder173_Mesh092"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder174_Mesh093.geometry}
          name="Cylinder174_Mesh093"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder175_Mesh094.geometry}
          name="Cylinder175_Mesh094"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder165_Mesh096.geometry}
          name="Cylinder165_Mesh096"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder166_Mesh097.geometry}
          name="Cylinder166_Mesh097"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder167_Mesh098.geometry}
          name="Cylinder167_Mesh098"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder168_Mesh099.geometry}
          name="Cylinder168_Mesh099"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder169_Mesh100.geometry}
          name="Cylinder169_Mesh100"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder099_Mesh102.geometry}
          name="Cylinder099_Mesh102"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder100_Mesh103.geometry}
          name="Cylinder100_Mesh103"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder101_Mesh104.geometry}
          name="Cylinder101_Mesh104"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder102_Mesh105.geometry}
          name="Cylinder102_Mesh105"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder104_Mesh107.geometry}
          name="Cylinder104_Mesh107"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder105_Mesh108.geometry}
          name="Cylinder105_Mesh108"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder106_Mesh109.geometry}
          name="Cylinder106_Mesh109"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder107_Mesh110.geometry}
          name="Cylinder107_Mesh110"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder108_Mesh111.geometry}
          name="Cylinder108_Mesh111"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder109_Mesh112.geometry}
          name="Cylinder109_Mesh112"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder093_Mesh114.geometry}
          name="Cylinder093_Mesh114"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder094_Mesh115.geometry}
          name="Cylinder094_Mesh115"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder095_Mesh116.geometry}
          name="Cylinder095_Mesh116"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder096_Mesh117.geometry}
          name="Cylinder096_Mesh117"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder098_Mesh119.geometry}
          name="Cylinder098_Mesh119"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder087_Mesh120.geometry}
          name="Cylinder087_Mesh120"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder088_Mesh121.geometry}
          name="Cylinder088_Mesh121"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder089_Mesh122.geometry}
          name="Cylinder089_Mesh122"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder090_Mesh123.geometry}
          name="Cylinder090_Mesh123"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder092_Mesh125.geometry}
          name="Cylinder092_Mesh125"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder147_Mesh407.geometry}
          name="Cylinder147_Mesh407"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder148_Mesh408.geometry}
          name="Cylinder148_Mesh408"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder149_Mesh409.geometry}
          name="Cylinder149_Mesh409"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder150_Mesh410.geometry}
          name="Cylinder150_Mesh410"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder151_Mesh411.geometry}
          name="Cylinder151_Mesh411"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder159_Mesh413.geometry}
          name="Cylinder159_Mesh413"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder160_Mesh414.geometry}
          name="Cylinder160_Mesh414"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder161_Mesh415.geometry}
          name="Cylinder161_Mesh415"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder162_Mesh416.geometry}
          name="Cylinder162_Mesh416"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder163_Mesh417.geometry}
          name="Cylinder163_Mesh417"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder153_Mesh419.geometry}
          name="Cylinder153_Mesh419"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder154_Mesh420.geometry}
          name="Cylinder154_Mesh420"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder155_Mesh421.geometry}
          name="Cylinder155_Mesh421"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder156_Mesh422.geometry}
          name="Cylinder156_Mesh422"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder157_Mesh423.geometry}
          name="Cylinder157_Mesh423"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder117_Mesh425.geometry}
          name="Cylinder117_Mesh425"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder118_Mesh426.geometry}
          name="Cylinder118_Mesh426"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder119_Mesh427.geometry}
          name="Cylinder119_Mesh427"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder120_Mesh428.geometry}
          name="Cylinder120_Mesh428"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder121_Mesh429.geometry}
          name="Cylinder121_Mesh429"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder111_Mesh431.geometry}
          name="Cylinder111_Mesh431"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder112_Mesh432.geometry}
          name="Cylinder112_Mesh432"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder113_Mesh433.geometry}
          name="Cylinder113_Mesh433"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder114_Mesh434.geometry}
          name="Cylinder114_Mesh434"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder115_Mesh435.geometry}
          name="Cylinder115_Mesh435"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder129_Mesh437.geometry}
          name="Cylinder129_Mesh437"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder130_Mesh438.geometry}
          name="Cylinder130_Mesh438"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder131_Mesh439.geometry}
          name="Cylinder131_Mesh439"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder132_Mesh440.geometry}
          name="Cylinder132_Mesh440"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder133_Mesh441.geometry}
          name="Cylinder133_Mesh441"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder123_Mesh443.geometry}
          name="Cylinder123_Mesh443"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder124_Mesh444.geometry}
          name="Cylinder124_Mesh444"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder125_Mesh445.geometry}
          name="Cylinder125_Mesh445"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder126_Mesh446.geometry}
          name="Cylinder126_Mesh446"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder127_Mesh447.geometry}
          name="Cylinder127_Mesh447"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder135_Mesh449.geometry}
          name="Cylinder135_Mesh449"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder136_Mesh450.geometry}
          name="Cylinder136_Mesh450"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder137_Mesh451.geometry}
          name="Cylinder137_Mesh451"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder138_Mesh452.geometry}
          name="Cylinder138_Mesh452"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder139_Mesh453.geometry}
          name="Cylinder139_Mesh453"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder141_Mesh455.geometry}
          name="Cylinder141_Mesh455"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder142_Mesh456.geometry}
          name="Cylinder142_Mesh456"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder143_Mesh457.geometry}
          name="Cylinder143_Mesh457"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder144_Mesh458.geometry}
          name="Cylinder144_Mesh458"
        />
        <mesh
          material={materials.Brushed_Metal_2}
          geometry={nodes.Cylinder145_Mesh459.geometry}
          name="Cylinder145_Mesh459"
        />
        <mesh material={materials.monitor} geometry={nodes.Box110_Mesh126.geometry} name="Box110_Mesh126" />
        <mesh material={materials.monitor} geometry={nodes.Box060_Mesh511.geometry} name="Box060_Mesh511" />
        <mesh material={materials.monitor_timeline} geometry={nodes.Box119_Mesh128.geometry} name="Box119_Mesh128" />
        <mesh material={materials.Right_Front_Graphic} geometry={nodes.Box016_Mesh130.geometry} name="Box016_Mesh130" />
        <mesh material={materials.Right_Front_Graphic} geometry={nodes.Arc007_Mesh131.geometry} name="Arc007_Mesh131" />
        <mesh material={materials.Right_Front_Graphic} geometry={nodes.Box015_Mesh132.geometry} name="Box015_Mesh132" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box031_Mesh136.geometry} name="Box031_Mesh136" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box032_Mesh137.geometry} name="Box032_Mesh137" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box033_Mesh138.geometry} name="Box033_Mesh138" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box025_Mesh142.geometry} name="Box025_Mesh142" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box026_Mesh143.geometry} name="Box026_Mesh143" />
        <mesh material={materials.Architectural_Glass} geometry={nodes.Box027_Mesh144.geometry} name="Box027_Mesh144" />
        <mesh
          material={materials.Architectural_Glass}
          geometry={nodes.glass004_Mesh376.geometry}
          name="glass004_Mesh376"
        />
        <mesh
          material={materials.Architectural_Glass}
          geometry={nodes.glass000_Mesh006.geometry}
          name="glass000_Mesh006"
        />
        <mesh material={materials.Chrome} geometry={nodes.BASE009_Mesh373.geometry} name="BASE009_Mesh373" />
        <mesh material={materials.Chrome} geometry={nodes.BASE010_Mesh374.geometry} name="BASE010_Mesh374" />
        <mesh
          material={materials.Chrome}
          geometry={nodes.steel_legs004_Mesh378.geometry}
          name="steel_legs004_Mesh378"
        />
        <mesh material={materials.Chrome} geometry={nodes.Loft009_Mesh379.geometry} name="Loft009_Mesh379" />
        <mesh material={materials.Chrome} geometry={nodes.Loft010_Mesh380.geometry} name="Loft010_Mesh380" />
        <mesh material={materials.Chrome} geometry={nodes.BASE009001_Mesh003.geometry} name="BASE009001_Mesh003" />
        <mesh material={materials.Chrome} geometry={nodes.BASE010001_Mesh004.geometry} name="BASE010001_Mesh004" />
        <mesh
          material={materials.Chrome}
          geometry={nodes.steel_legs000_Mesh008.geometry}
          name="steel_legs000_Mesh008"
        />
        <mesh material={materials.Chrome} geometry={nodes.Loft009001_Mesh009.geometry} name="Loft009001_Mesh009" />
        <mesh material={materials.Chrome} geometry={nodes.Loft010001_Mesh010.geometry} name="Loft010001_Mesh010" />
        <mesh material={materials.marble} geometry={nodes.Rectangle005_Mesh382.geometry} name="Rectangle005_Mesh382" />
        <mesh material={materials.carpet} geometry={nodes.Box092_Mesh383.geometry} name="Box092_Mesh383" />
        <mesh material={materials.Elzonris_green} geometry={nodes.Line063_Mesh500.geometry} name="Line063_Mesh500" />
        <mesh material={materials['monitor.001']} geometry={nodes.Box061_Mesh512.geometry} name="Box061_Mesh512" />
        <mesh material={materials.now_approved} geometry={nodes.Arc013_Mesh514.geometry} name="Arc013_Mesh514" />
        <mesh material={materials.now_approved} geometry={nodes.Box118_Mesh515.geometry} name="Box118_Mesh515" />
        <mesh material={materials.now_approved} geometry={nodes.Box115_Mesh516.geometry} name="Box115_Mesh516" />
        <mesh material={materials.now_approved} geometry={nodes.Box116_Mesh517.geometry} name="Box116_Mesh517" />
        <mesh material={materials.now_approved} geometry={nodes.Arc014_Mesh518.geometry} name="Arc014_Mesh518" />
        <mesh material={materials.now_approved} geometry={nodes.Box117_Mesh519.geometry} name="Box117_Mesh519" />
        <mesh material={materials['Material.001']} geometry={nodes.Plane.geometry} name="Plane" />
      </scene>
    </group>
  )
}
